---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
library(stringr)
library(janitor)
```

```{r}
library(here)

candy_2015 <- read_excel(here("raw_data/candy_ranking_data/boing-boing-candy-2015.xlsx"))

```

```{r}
candy_2016 <- read_excel(here("raw_data/candy_ranking_data/boing-boing-candy-2016.xlsx"))

head(candy_2016)
```

```{r}
candy_2017 <- read_excel(here("raw_data/candy_ranking_data/boing-boing-candy-2017.xlsx"))

head(candy_2017)
```

```{r}
candy_2015_headings <- candy_2015 %>% 
  clean_names()
```

```{r}
candy_2015_headings %>% 
  colnames()
```



```{r}
candy_2016_headings <- candy_2016 %>% 
  clean_names()

colnames(candy_2016_headings)
```



```{r}
candy_2017_headings <- candy_2017 %>% 
  clean_names() 

candy_2017_headings_test <- colnames(candy_2017_headings) %>% 
  str_replace_all(pattern = "q[0-9]_", replacement = "")

```

```{r}
names(candy_2017_headings) <- candy_2017_headings_test
```

```{r}
candy_2015_subset <- candy_2015_headings %>% 
  select(-c(1, 12, 18, 23, 26, 27, 28, 33:35, 38, 41, 45, 88, 90, 93, 94, 95, 97:114, 116:124))

```

```{r}
candy_2016_subset <- candy_2016_headings %>% 
  select(-c(1, 6, 12, 15, 21, 22, 26, 27, 31, 32, 38, 39, 43, 49, 79, 102, 104, 105, 107:123))

```

```{r}
candy_2017_subset <- candy_2017_headings %>% 
  select(-c(1, 6, 12, 15, 21 , 22, 26, 27, 31, 32, 38, 39, 43, 49, 69, 81, 86, 105, 107, 108, 110:120))
```

```{r}
candy_2015_subset <- candy_2015_subset %>% 
  add_column("gender" = "unknown", "country" = "unknowm", "coffee_crisp" = "no_rating", "dove_bars" = "no_rating", "mike_and_ike" = "no_rating" , "blue_m_ms" = "no_rating", "red_m_ms" = "no_rating", "independent_m_ms" = "no_rating", "mr_goodbar" = "no_rating", "peeps" = "no_rating", "reeses_pieces" = "no_rating", "sourpatch_kids_i_e_abominations_of_nature" = "no_rating", "sweet_tarts" = "no_rating", "take_5" = "no_rating", "tic_tacs" = "no_rating", "whatchamacallit_bars" = "no_rating") %>% 
  rename("age" = "how_old_are_you", "going_out"= "are_you_going_actually_going_trick_or_treating_yourself", "100_grand_bar" = "x100_grand_bar", "bonkers_the_candy" = "bonkers", "boxo_raisins"= "box_o_raisins", "hersheys_dark_chocolate" = "dark_chocolate_hershey", "hersheys_kisses" = "hershey_s_kissables", "licorice_yes_black" = "licorice", "black_and_orange_wrapper" = "anonymous_brown_globs_that_come_in_black_and_orange_wrappers", "green_party_m_ms" = "mint_m_ms",                                                             ) %>% 
  mutate(age = as.integer(age))
```


```{r}
colnames(candy_2015_subset)
```

```{r}
candy_2016_subset <- candy_2016_subset %>% 
  add_column("take_5" = "no_rating", "bubble_gum" = "no_rating", "green_party_m_ms" = "no_rating", "mint_leaves" = "no_rating", "runts" = "no_rating", "ribbon_candy" = "no_rating", "peanut_butter_bars" = "no_rating") %>% 
  rename("age" = "how_old_are_you", "gender" = "your_gender", "country" = "which_country_do_you_live_in", "independent_m_ms" = "third_party_m_ms","going_out" = "are_you_going_actually_going_trick_or_treating_yourself", "100_grand_bar" = "x100_grand_bar", "sweetums" = "sweetums_a_friend_to_diabetes", "black_and_orange_wrapper" = "anonymous_brown_globs_that_come_in_black_and_orange_wrappers"                                                             ) %>% 
  mutate(age = as.integer(age))
```

```{r}
colnames(candy_2016_subset)
```

```{r}
candy_2017_subset <- candy_2017_subset %>% 
  add_column("bubble_gum" = "no_rating", "mint_leaves" = "no_rating", "runts" = "no_rating", "ribbon_candy" = "no_rating", "peanut_butter_bars" = "no_rating", "mary_janes" = "no_rating") %>% 
  rename("sweetums" = "sweetums_a_friend_to_diabetes", "black_and_orange_wrapper" = "anonymous_brown_globs_that_come_in_black_and_orange_wrappers_a_k_a_mary_janes"                                                             ) %>% 
  mutate(age = as.integer(age))
```


```{r}
colnames(candy_2017_subset)
```

```{r}
candy_2015_reorder <- candy_2015_subset %>% 
  select(2, 80, 1, 81, 4:10, 3, 12, 13, 15, 17, 68, 16, 82, 20, 83, 21:25, 32, 19, 27, 26, 28, 29, 44, 55, 56, 30, 31, 42, 33:40:84, 41, 51, 61, 60, 85:87, 43, 57, 58, 88, 79, 47, 48, 49, 89, 50, 46, 52, 90, 45, 64, 65, 66, 67, 18, 91, 69, 70, 92, 71, 72, 94, 73, 74, 53, 76, 77, 14, 95, 78, 93, 11, 62, 59, 54, 63, 75)
```



 
```{r}
candy_2015_reorder <- candy_2015_reorder %>% 
  select(1:39, 41, 40, 42:95)
```
 
```{r}
colnames(candy_2015_reorder)
```
 
```{r}
candy_2017_reorder <- candy_2017_subset %>% 
  select(1:44, 95, 45:52, 54:79, 81:89, 80, 90, 53, 91:94)
```

```{r}
colnames(candy_2017_reorder)
```

```{r}

```

